export const copy = {
  app: {
    name: "DAX",
    tagline: "Fast-paced multiplayer card game",
    description: "Play DAX online with 2–4 players. Real-time UNO-style card game with 30-second turns.",
  },
  cta: {
    playNow: "Play now",
    startGame: "Start game",
    createRoom: "Create room",
    joinRoom: "Join room",
    readyUp: "Ready up",
    playCard: "Play card",
    drawCard: "Draw card",
    leaveTable: "Leave table",
    rematch: "Rematch",
  },
  toast: {
    roomCreated: (code: string) => `Room ${code} created`,
    roomJoined: "Joined room",
    codeCopied: "Code copied",
    invalidCode: "Enter a valid 6-digit room code",
    roomNotFound: "Room not found — check the code",
    createFailed: "Couldn't create room. Try again.",
    joinFailed: "Couldn't join room. Try again.",
    invalidCard: "Can't play that — match color or number",
    unoCalled: "UNO! called",
    unoEarly: "Wait until you have 1 card, then call UNO!",
    unoOnlyOne: "Call UNO only when you have one card left",
    unoCalledOut: (name: string) => `Called out ${name}!`,
    timeUp: "Time's up — turn skipped",
    reconnecting: "Reconnecting…",
    connectionLost: "Connection lost. Reconnecting…",
    findingTable: "Finding a table…",
    demoStart: "Starting demo match…",
  },
  errors: {
    roomNotFound: "No room found for that code",
    needTwoPlayers: "Need at least 2 players",
    allReady: "All players must be ready",
  },
  labels: {
    turnTimer: "Turn timer",
    drawPile: "Draw pile",
    discardPile: "Discard pile",
    callUno: "Call UNO",
    wildPick: "Choose a color",
    spectators: "Spectators",
  },
} as const;
